### ISSUE TITLE
Benefits over using Bluebird?

### ISSUE THREAD

**Issue by raine** [briancavalier/creed#3] opened 2015-09-20 10:56 UTC
Hello,

As someone who is used to having Bluebird around, I'm wondering what creed brings over using BB?

The [example converted to use Bluebird](https://gist.github.com/ea8c550d45f09ba07c0a) is pretty similar.

Perhaps I misunderstood and purpose of creed is only to augment native Promises with less powerful API than Bluebird's? I'd imagine it's less heavy at least, which could be a big deal in the browser side.

**Comment by briancavalier** [comment] 2015-09-21 00:46
Hey @raine.  Creed is focused on functional programming.  Its promise is implemented as a fully parametric algebraic data type.  One of its goals is to provide an algebraic promise that implements algebraic types (functor, applicative, etc.), while also providing ES6 and Promises/A+ compatibility (e.g. via `then`).  Whether someone considers these algebraic APIs to be more or less "powerful" than another promise lib is likely subjective.  It does, imho, make for nice, standard programming idioms when used with other libs that support algebraic APIs.

Creed is about 4k min+gzip.  It intentionally offers a smaller feature set.  I like to think that much of creed's compactness and performance comes from an elegant internal architecture and relatively simple code.  Of course, "elegant" and "simple" are mostly subjective, too :)

It probably depends on what you're looking for as to whether these things are benefits or not.  If you're into FP and looking for a promise that fits nicely into that ecosystem (fantasy-land, ramda, folktale, etc.), while also offering ultra-high performance and ES6/Promises/A+ compat, creed could be worth a closer look.

**Comment by bergus** [comment] 2015-09-21 11:16
> Of course, "elegant" and "simple" are mostly subjective, too

Objectivity is gained by many people having the same subjective view - and having read the code, I can confirm both :-)

**Comment by briancavalier** [comment] 2015-09-21 11:35
@bergus :smile:

**Comment by briancavalier** [comment] 2015-10-01 00:55
@raine I'm closing this since it's been a while since we've heard from you, and this isn't specifically a bug.  Please do feel free to continue the discussion, though, if you have more questions.  Thanks!

**Closed by briancavalier** 2015-10-01 00:55 UTC
